### DISCUSSION TITLE
Could you provide an example of docker.compose to use this image correctly.

### DISCUSSION THREAD

**Discussion by terabytesoftw** [gvenzl/oci-oracle-xe#165] [Q&A]
Thks.

**Comment by pranithan-kang** [comment]
In my case, I use this:

```yaml
services:

  # Oracle service (label used to access the service container)
  my-oracle-db:
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:21.3.0-slim
    restart: unless-stopped
    volumes:
      # - oracle-data:/opt/oracle/oradata

    # Provide passwords and other environment variables to container
    environment:
      ORACLE_RANDOM_PASSWORD: true
      # APP_USER: oracle-user
      # APP_USER_PASSWORD: 123456
    ports:
      - 1521:1521
```
