### DISCUSSION TITLE
How do I initialize the database correctly?

### DISCUSSION THREAD

**Discussion by dventimihasura** [gvenzl/oci-oracle-xe#182] [Q&A] [answered]
Hi!  Thanks so much for offering this repo and Docker image.  Sorry, but I'm new to Oracle and I don't understand how to initialize the database correctly.  I know the documentation [says](https://github.com/gvenzl/oci-oracle-xe#startup-scripts) startup scripts in `docker-entrypoint-startdb.d` will do this, and I believe it.  In fact, it even seems to work insofar as the startup logs show that my scripts are running, tables are being created, and data are being inserted.  The trouble is, afterward when I log into the database, I can't find the tables.  It probably means they're being created in a database and/or a schema in a way I don't understand.  Anyway, here's the `environment` stanza in my `docker-compose.yaml` file.

```yaml
    environment:
      ORACLE_PASSWORD: chinook
      ORACLE_DATABASE: chinook
      APP_USER: chinook
      APP_USER_PASSWORD: chinook
```

Afterward, I connect to the database with JDBC and this url:  `jdbc:oracle:thin:@localhost:1522/chinook` and userid `chinook` and password `chinook` but for the life of me I can't find the tables my scripts created (`Album`, `Track`, etc.).

Should I connect to a different database, or as a different user?  Sorry, I'm really confused here.  Thanks!
