### ISSUE TITLE
User created during init script can't be authenticated despite `GRANT CREATE SESSION`

### ISSUE THREAD

**Issue by GavinRay97** [gvenzl/oci-oracle-xe#197]
Hiya,

I am trying to use the popular "Chinook" test database with Oracle:
- https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Oracle.sql

I have mounted the `Chinook_Oracle.sql` to `/container-entrypoint-initdb.d/chinook.sql`
```sql
-- Added this from the example in the README
ALTER SESSION SET CONTAINER=XEPDB1;

-- Below is the existing Chinook code
CREATE USER chinook
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to chinook;
GRANT resource to chinook;
GRANT create session TO chinook;
GRANT create table TO chinook;
GRANT create view TO chinook;
````

However oddly enough, when I try to connect as this user, I get an error that the user lacks the `CREATE SESSION` privilege, which is strange:
```SH
$ sqlplus chinook/p4ssw0rd@localhost:1521/XEPDB1

SQL*Plus: Release 21.0.0.0.0 - Production on Mon Mar 20 15:43:19 2023
Version 21.9.0.0.0

Copyright (c) 1982, 2022, Oracle.  All rights reserved.

ERROR:
ORA-01045: user CHINOOK lacks CREATE SESSION privilege; logon denied
```

Is there something else that needs to be done in order to connect as this user? :thinking:
Thank you =)

---

Here is the full Docker Compose configuration I am using:
```yaml
oracle:
    image: gvenzl/oracle-xe:21.3.0-slim
    restart: always
    environment:
        ORACLE_PASSWORD: Password123#
    ports:
        - "1521:1521"
    volumes:
        - ./db/Chinook_Oracle.sql:/container-entrypoint-initdb.d/chinook.sql
```
