### ISSUE TITLE
Permission denied on Github Workflow

### ISSUE THREAD

**Issue by xkosubek** [gvenzl/oci-oracle-xe#234]
Hello,

thanks for that image!
I try to include the container in a Github Workflow and mount a directory for init scripts.

```
services:
      # Oracle service (label used to access the service container)
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-xe:latest
        # Provide passwords and other environment variables to container
        env:
          ORACLE_RANDOM_PASSWORD: true
          # APP_USER: geo_test
          # APP_USER_PASSWORD: geo_test
        # Forward Oracle port
        ports:
          - 1521:1521
        volumes:
          - ${{ github.workspace }}/tests/data/oracle/init-db:/container-entrypoint-startdb.d
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
```
In the folder i have one script with the name 01-create-user.sql.

```
CREATE USER geo_test IDENTIFIED BY geo_test QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, DBA TO geo_test;
```

The Github workflow ends with an permission denied error:
```
Deleting the contents of '/home/runner/work/pygeoapi/pygeoapi'
Error: Command failed: rm -rf /home/runner/work/pygeoapi/pygeoapi/tests
rm: cannot remove '/home/runner/work/pygeoapi/pygeoapi/tests/data/oracle/init-db': Permission denied
```

Has anybody an idea how i can fix that error?
