### ISSUE TITLE
error after restarting container

### ISSUE THREAD

**Issue by HaniBikdeli** [gvenzl/oci-oracle-xe#243]
Hi there,

I have recently restarted my oracle container which was based on the image gvenzl/oracle-xe:21-slim.

And i have done so using this docker compose file 

```
version: '2'
services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    restart: always
    environment:
      - ORACLE_PASSWORD=root
    ports:
      - 1521:1521
    volumes:
      - oracle-volume:/opt/oracle/oradata
volumes:
   oracle-volume:
```

However after restarting this container i have encountered this error

`ORA-01157: cannot identify/lock data file 20 - see DBWR trace file ORA-01110: data file 20: '/opt/oracle/homes/OraDBHome21cXE/dbs/{filename}.dat'`

Apparently the datafiles i had created are missing. Is there a way i can fix this?
