### ISSUE TITLE
APP_USER Not Created in XE on 18-slim

### ISSUE THREAD

**Issue by theory** [gvenzl/oci-oracle-xe#46]
I got a [GitHub Workflow](https://github.com/sqitchers/sqitch/blob/test-oracle/.github/workflows/oracle.yml) working for 11-slim but not 18-slim. [Here is the run](https://github.com/sqitchers/sqitch/actions/runs/1432076061). The error on 18-slim is:

```
ORA-01918: user 'SQITCHTEST' does not exist
```

This user should be created by the service configuration:

``` yaml
    services:
      oracle:
        image: gvenzl/oracle-xe:${{ matrix.oracle.version }}-slim
        ports: [ 1521 ]
        env:
          ORACLE_PASSWORD: sqitchtest
          APP_USER: sqitchtest
          APP_USER_PASSWORD: sqitchtest
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
```

This works well in 11-slim but not 18-slim. Note that for both I'm using the SID `XE`; maybe the user is created in some other database in 18-slim? I've tried connecting to `XEPDB1` instead, but that does not seem to exist, returning

```
ORA-12505: TNS:listener does not currently know of SID given in connect descriptor (DBD ERROR: OCIServerAttach)
```
