### ISSUE TITLE
How can I turn off DISABLE_OOB in 21c+ images?

### ISSUE THREAD

**Issue by kubo** [gvenzl/oci-oracle-xe#75]
Some my tests check canceling by [`OCIBreak`](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnoci/miscellaneous-functions.html#GUID-A414B5DE-07A3-4593-A448-B6023F87C2D0). However 21c+ images set `DISABLE_OOB` in sqlnet.ora in the database side and the tests fail. I would be happy if `DISABLE_OOB` could be optionally turned off in the latest images.

I put the following step in github actions to set the environment variable [`TWO_TASK`](https://www.orafaq.com/wiki/TWO_TASK) for later steps. The tests succeed when the docker image is 18c.
```
      - name: Get the Oracle container IP address
        env:
          ORACLE_SERVICE_ID: ${{ job.services.oracle.id }}
        run: |
          ORACLE_IP_ADDRESS=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{println .IPAddress}}{{end}}' $ORACLE_SERVICE_ID)
          if test -z "$ORACLE_IP_ADDRESS"; then
              echo "Cannot get ORACLE_IP_ADDRESS."
              docker inspect $ORACLE_SERVICE_ID
              exit 1
          fi
          echo TWO_TASK=//$ORACLE_IP_ADDRESS:1521/XEPDB1 >> $GITHUB_ENV
```

**Comment by kubo** [comment]
I resolve it by adding the following step in github actions.
```yaml
      - name: Enable OOB
        env:
          ORACLE_SERVICE_ID: ${{ job.services.oracle.id }}
        run: |
          docker exec $ORACLE_SERVICE_ID sed -i 's/^DISABLE_OOB/#DISABLE_OOB/; s/^BREAK_POLL_SKIP=1000/#BREAK_POLL_SKIP=1000/' /opt/oracle/oradata/dbconfig/XE/sqlnet.ora
          docker exec $ORACLE_SERVICE_ID lsnrctl reload
```
