### ISSUE TITLE
'ls: cannot acess 'container-entrypoint-initdb.d': Operation not permitted

### ISSUE THREAD

**Issue by SeanM96** [gvenzl/oci-oracle-xe#87]
I am trying to mount some .sql files to my container as start up scripts for my db, docker compose:

```
oracle:
  image: gvenzl/oracle-xe:11
  environment:
    APP_USER: TEST_USER
    APP_USER_PASSWORD: password
    ORACLE_RANDOM_PASSWORD: enabled
  volumes:
    - "./oracle:/container-entrypoint-initdb.d"
  ports:
    - 1521:1521
```

The container starts fine, but logs the message stated in the title. The volume mounts, as I can cat it in the container, but does not run the SQL script. I can connect to the database via SQL developer.
