### ISSUE TITLE
Container initiates properly, But the data does not exist on the user provided schema in 11-slim

### ISSUE THREAD

**Issue by Mellywins** [gvenzl/oci-oracle-xe#97]
I'm running into an issue using the oracle-xe:11-slim.
```shell
oracle_db_1           | CONTAINER: Creating database application user.
oracle_db_1           | 
oracle_db_1           | User created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Grant succeeded.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | CONTAINER: Executing user defined scripts...
oracle_db_1           | CONTAINER: running /container-entrypoint-initdb.d/DXCLOUD_INT.sql ...
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | 
oracle_db_1           | Table created.
oracle_db_1           | 
oracle_db_1           | CONTAINER: DONE: running /container-entrypoint-initdb.d/DXCLOUD_INT.sql
oracle_db_1           | 
oracle_db_1           | CONTAINER: DONE: Executing user defined scripts.
```
After connecting with the user I declared in my docker-compose with the following service:
```YAML
  oracle_db:
    build:
      context: .
      dockerfile: docker/oracle.Dockerfile
    environment:
      - ORACLE_RANDOM_PASSWORD
      - APP_USER
      - APP_USER_PASSWORD
    ports:
      - "1521:1521"
    networks:
      - ddxcloud_net
    volumes:
      - oracle_data:/u01/app/oracle/oradata
```
The data tables do not exist.
I used datagrip to connect to the DB and querry the tables, Couldn't find them.
I also used sqlplus from within the container then ran the following:
```sql
SELECT table_name
FROM user_tables
ORDER BY table_name;
```
Couldn't find anything either. The issue is that nothing fails, but I still cant find the tables i created.
I used this simple dockerfile
```Dockerfile
FROM gvenzl/oracle-xe:11-slim
COPY DXCLOUD_INT.sql /container-entrypoint-initdb.d/DXCLOUD_INT.sql
```
